/**
 * KREA2 — Image → Prompt → Image (Gemma-4 via Ollama).
 * LoadImage → OllamaChat (vision) → the generated description directly
 * feeds the positive CLIPTextEncode of a classic KREA2 t2i.
 * Derived from a proven personal workflow: same local Ollama model, same
 * system prompt (verbatim), keep_alive 0 (the model is unloaded after the
 * call — no RAM contention with KREA2).
 *
 * Requires Ollama running on the Mac (127.0.0.1:11434 — never exposed on
 * the tailnet, ComfyUI calls it on localhost) and the comfyui-ollama custom
 * node. OllamaConnectivityV2's `model` combo is an empty tuple server-side
 * → API validation does not check it (verified in the server's
 * execution.py).
 *
 * A ShowText (custom-scripts) is wired as a side output: the generated
 * prompt surfaces in /history (node 13 outputs) and in the PNG.
 * OllamaChat has no IS_CHANGED → in a ×N batch, ComfyUI caches the
 * description: a single Gemma call, N seeds (variants of the same prompt).
 */

import type { PromptGraph } from '../api/types';
// Verbatim KREA2 system prompt, now in prompt-styles (shared with
// krea2-img2prompt and text2prompt). Here the generated prompt feeds the
// embedded KREA2 t2i → no style select, KREA2 is the only sensible style.
import { IMAGE2PROMPT_SYSTEM } from './prompt-styles';
import type { WorkflowManifest } from './types';

const graph: PromptGraph = {
  '1': {
    class_type: 'UNETLoader',
    inputs: {
      unet_name: 'krea2_turbo_bf16.safetensors',
      weight_dtype: 'default',
    },
    _meta: { title: 'Load Krea 2 Turbo (diffusion model)' },
  },
  '2': {
    class_type: 'CLIPLoader',
    inputs: {
      clip_name: 'qwen3vl_4b_fp8_scaled.safetensors',
      type: 'krea2',
    },
    _meta: { title: 'Load Qwen3-VL text encoder (type: krea2)' },
  },
  '3': {
    class_type: 'VAELoader',
    inputs: {
      vae_name: 'qwen_image_vae.safetensors',
    },
    _meta: { title: 'Load Qwen Image VAE' },
  },
  '4': {
    class_type: 'LoadImage',
    inputs: {
      image: '',
    },
    _meta: { title: 'Image to describe' },
  },
  '5': {
    class_type: 'OllamaConnectivityV2',
    inputs: {
      url: 'http://127.0.0.1:11434',
      model: 'gemma4-vision:latest',
      keep_alive: 0,
      keep_alive_unit: 'minutes',
    },
    _meta: { title: 'Local Ollama (Gemma-4, unloaded after the call)' },
  },
  '6': {
    class_type: 'OllamaChat',
    inputs: {
      connectivity: ['5', 0],
      images: ['4', 0],
      system: IMAGE2PROMPT_SYSTEM,
      prompt: '',
      think: false,
      format: 'text',
    },
    _meta: { title: 'Gemma-4 describes the image → KREA2 prompt' },
  },
  '7': {
    class_type: 'CLIPTextEncode',
    inputs: {
      clip: ['2', 0],
      text: ['6', 0],
    },
    _meta: { title: 'Positive prompt (generated by Gemma-4)' },
  },
  '8': {
    class_type: 'CLIPTextEncode',
    inputs: {
      clip: ['2', 0],
      text: 'blurry, low quality, cartoon, watermark, text, deformed',
    },
    _meta: { title: 'Negative prompt (unused at cfg 1)' },
  },
  '9': {
    class_type: 'EmptySD3LatentImage',
    inputs: {
      width: 1024,
      height: 1024,
      batch_size: 1,
    },
    _meta: { title: 'Empty latent (16-ch)' },
  },
  '10': {
    class_type: 'KSampler',
    inputs: {
      model: ['1', 0],
      positive: ['7', 0],
      negative: ['8', 0],
      latent_image: ['9', 0],
      seed: 0,
      steps: 8,
      cfg: 1.0,
      sampler_name: 'euler',
      scheduler: 'simple',
      denoise: 1.0,
    },
    _meta: { title: 'Turbo sampler (8 steps, cfg 1)' },
  },
  '11': {
    class_type: 'VAEDecode',
    inputs: {
      samples: ['10', 0],
      vae: ['3', 0],
    },
    _meta: { title: 'VAE Decode' },
  },
  '12': {
    class_type: 'SaveImage',
    inputs: {
      images: ['11', 0],
      filename_prefix: 'komfy/krea2-image2prompt',
    },
    _meta: { title: 'Save Image' },
  },
  // Side output: the generated prompt is visible in /history and the PNG.
  '13': {
    class_type: 'ShowText|pysssss',
    inputs: {
      text: ['6', 0],
    },
    _meta: { title: 'Generated prompt (visible in the history)' },
  },
};

export const krea2Image2Prompt: WorkflowManifest = {
  id: 'krea2-image2prompt',
  name: 'wf.i2p2i.name',
  description: 'wf.i2p2i.description',
  icon: 'eye-outline',
  graph,
  saveNodeId: '12',
  fields: [
    {
      kind: 'image',
      key: 'image',
      label: 'wf.i2p.image',
      target: { nodeId: '4', input: 'image' },
      required: true,
      hint: 'wf.common.needsOllama',
    },
    {
      kind: 'text',
      key: 'consigne',
      label: 'wf.i2p.instruction',
      target: { nodeId: '6', input: 'prompt' },
      default: '',
      placeholder: 'wf.i2p.instructionPlaceholder',
      multiline: true,
      hint: 'wf.i2p.instructionHint',
    },
    {
      kind: 'dimensions',
      key: 'format',
      label: 'wf.common.dimensions',
      widthTarget: { nodeId: '9', input: 'width' },
      heightTarget: { nodeId: '9', input: 'height' },
      options: [
        { width: 1024, height: 1024 },
        { width: 1216, height: 832 },
        { width: 1344, height: 896 },
        { width: 1536, height: 1024 },
        { width: 1664, height: 960 },
        { width: 1728, height: 976 },
        { width: 1792, height: 1008 },
        { width: 1920, height: 1080 },
      ],
      default: { width: 1024, height: 1024 },
    },
    {
      kind: 'loras',
      key: 'loras',
      label: 'LoRAs',
      hint: 'wf.common.lorasHint',
      modelSource: { nodeId: '1', output: 0 },
      modelTargets: [{ nodeId: '10', input: 'model' }],
      maxCount: 4,
      defaultStrength: 0.9,
    },
    {
      kind: 'number',
      key: 'steps',
      label: 'Steps',
      target: { nodeId: '10', input: 'steps' },
      default: 8,
      min: 1,
      max: 30,
      integer: true,
    },
    {
      kind: 'seed',
      key: 'seed',
      label: 'Seed',
      target: { nodeId: '10', input: 'seed' },
    },
  ],
};
